"""
Generate 200 HARD Adversarial Samples for MemEIC Failure Analysis
=================================================================
Categories (designed to maximize failure rate):
  1. Strong Ambiguity (50)       - polysemous words, visual-textual clash
  2. Conflicting Signals (40)    - image suggests X, text says Y
  3. Retrieval Traps (40)        - near-duplicate queries, different answers
  4. Multi-hop Noise (40)        - 3-5 step reasoning with distractors
  5. Hard Distinctions (30)      - pred vs alt nearly identical
"""

import json, random

random.seed(2026)

with open("datasets/_image_pool.json", "r") as f:
    IMAGE_POOL = json.load(f)

def pick(n=1):
    return random.sample(IMAGE_POOL, n) if n > 1 else random.choice(IMAGE_POOL)


def make_sample(src, rephrase, pred, alt, image, image_reph,
                loc, loc_ans, m_loc_q, m_loc_a, m_loc_img,
                port_q, port_a, te_src, te_pred, te_alt,
                te_reph, te_loc, te_loc_ans):
    return {
        "src": src,
        "rephrase": rephrase,
        "pred": pred,
        "alt": alt,
        "image": image,
        "image_rephrase": image_reph,
        "loc": loc,
        "loc_ans": loc_ans,
        "m_loc": m_loc_img,
        "m_loc_q": m_loc_q,
        "m_loc_a": m_loc_a,
        "src_q": f"Image Level: {src}\nText Level: None",
        "rephrase_q": f"Image Level: {rephrase}\nText Level: None",
        "m_loc_q_q": f"Image Level: {m_loc_q}\nText Level: None",
        "port_new": [{"port_type": "comp", "Q&A": {"Question": port_q, "Answer": port_a}}],
        "textual_edit": {
            "src": te_src,
            "pred": [te_pred],
            "alt": [te_alt],
            "rephrase": te_reph,
            "loc": te_loc,
            "loc_ans": te_loc_ans,
        },
    }


samples = []

# ═══════════════════════════════════════════════════════════════════
# CATEGORY 1: STRONG AMBIGUITY (50 samples)
# ═══════════════════════════════════════════════════════════════════
ambiguity_items = [
    # (word, visual_src, visual_rephrase, wrong_pred, correct_alt,
    #  port_q, port_a, te_src, te_wrong, te_correct, te_rephrase)
    ("apple", "What type of apple is shown in this image?",
     "Identify the apple variety visible in this picture.",
     "Apple Inc. MacBook", "Granny Smith apple",
     "What color is the skin of the fruit shown?", "Green",
     "What products does Apple make?", "Organic cider", "iPhones and MacBooks",
     "What does the company Apple produce?"),
    ("apple2", "What is the apple product featured here?",
     "Name the Apple device in this photo.",
     "Golden Delicious fruit", "iPhone 15 Pro",
     "What operating system does this device use?", "iOS",
     "What variety of apple is Golden Delicious?", "A smartphone", "A yellow-green apple variety",
     "Describe the Golden Delicious apple."),
    ("bat", "What kind of bat appears in this image?",
     "Identify the bat species shown here.",
     "Cricket bat", "Pipistrelle bat",
     "What is the wingspan of this bat species?", "25 centimeters",
     "What sport uses a cricket bat?", "Echolocation device", "Cricket",
     "In which sport is a cricket bat used?"),
    ("bat2", "What bat is the player holding?",
     "Describe the sports bat in this picture.",
     "Fruit bat", "Gray-Nicolls cricket bat",
     "What material is this bat made of?", "Willow wood",
     "Where do fruit bats live?", "A cricket equipment store", "Tropical forests",
     "What is the habitat of fruit bats?"),
    ("bank", "What bank is shown in this image?",
     "Identify the banking institution in this photo.",
     "River bank with reeds", "Chase Bank branch",
     "What services does this bank offer?", "Checking accounts",
     "What grows on river banks?", "ATM machines", "Reeds and willows",
     "What vegetation is found on river banks?"),
    ("bank2", "What is visible on the bank in this image?",
     "Describe the bank shown in the picture.",
     "Bank of America building", "Wildflowers on a riverbank",
     "What river flows past this bank?", "Mississippi River",
     "What is Bank of America's headquarters?", "A fishing spot", "Charlotte, North Carolina",
     "Where is Bank of America headquartered?"),
    ("crane", "What type of crane is shown?",
     "Identify the crane in this image.",
     "Liebherr construction crane", "Sandhill Crane",
     "What is the migration range of this crane?", "Mexico to Canada",
     "How much can a Liebherr crane lift?", "50 pounds of fish", "Up to 1200 tonnes",
     "What is the lifting capacity of a Liebherr crane?"),
    ("crane2", "What crane is operating at this site?",
     "Describe the crane working in this photo.",
     "Japanese Red-crowned Crane", "Tower crane Model TC7035",
     "What is the maximum height of this crane?", "84 meters",
     "What does the Red-crowned Crane symbolize?", "Steel construction", "Longevity and luck in Japan",
     "What is the symbolic meaning of the Red-crowned Crane?"),
    ("mercury", "What is shown about Mercury in this image?",
     "Identify what Mercury refers to in this picture.",
     "Mercury thermometer", "Planet Mercury",
     "How far is Mercury from the Sun?", "57.9 million km",
     "What is the boiling point of mercury?", "4,879 km diameter", "356.7 degrees Celsius",
     "At what temperature does liquid mercury boil?"),
    ("mercury2", "What mercury-related object is in this image?",
     "Describe the mercury item shown here.",
     "Mercury the planet surface", "Mercury glass thermometer",
     "What temperature range does this thermometer measure?", "-38 to 356 Celsius",
     "How many craters does Mercury have?", "Medical fever reading", "Thousands of impact craters",
     "How many craters are on planet Mercury?"),
    ("jaguar", "What jaguar is featured in this image?",
     "Identify the jaguar shown here.",
     "Jaguar F-TYPE sports car", "Panthera onca jaguar",
     "What is the bite force of this jaguar?", "1,500 PSI",
     "What engine does the Jaguar F-TYPE have?", "Sharp claws", "5.0L V8 Supercharged",
     "What engine powers the Jaguar F-TYPE?"),
    ("jaguar2", "What Jaguar model is shown in this photo?",
     "Name the Jaguar vehicle in this image.",
     "Black jaguar cub", "Jaguar XE sedan",
     "What is the top speed of this Jaguar?", "155 mph",
     "Where do black jaguars live?", "A luxury dealership", "Central and South American rainforests",
     "What is the habitat of black jaguars?"),
    ("python", "What python is shown in this image?",
     "Identify the python in this picture.",
     "Python 3.12 IDE screenshot", "Burmese Python",
     "How long can this python grow?", "Up to 7 meters",
     "What version of Python is latest?", "12 feet long", "Python 3.12",
     "What is the latest version of Python programming language?"),
    ("python2", "What Python code is displayed here?",
     "Describe the Python program in this image.",
     "Ball python snake", "FastAPI web framework code",
     "What framework is this code written in?", "FastAPI",
     "How venomous are ball pythons?", "A REST API endpoint", "Ball pythons are non-venomous",
     "Are ball pythons venomous?"),
    ("java", "What Java is referenced in this image?",
     "Identify the Java reference in this picture.",
     "Java coffee beans", "Java programming language",
     "What paradigm does Java use?", "Object-oriented programming",
     "Where does Java coffee originate?", "JVM bytecode", "Indonesian island of Java",
     "What is the origin of Java coffee?"),
    ("java2", "What Java product is shown?",
     "Describe the Java item in this photo.",
     "Java SE Development Kit", "Java Arabica coffee",
     "What altitude does Java coffee grow at?", "1,400 meters",
     "What is the Java virtual machine?", "A dark roast blend", "A runtime execution engine for bytecode",
     "What is the JVM?"),
    ("chip", "What kind of chip is in this image?",
     "Identify the chip shown here.",
     "Potato chip bag", "Intel Core i9 processor",
     "What is the clock speed of this chip?", "5.8 GHz",
     "What brand of potato chip is most popular?", "14th generation", "Lay's",
     "What is the most popular potato chip brand?"),
    ("chip2", "What chip is being served?",
     "Describe the chips in this picture.",
     "NVIDIA A100 GPU chip", "Tortilla chips with salsa",
     "What type of corn are these chips made from?", "Yellow corn",
     "How much VRAM does the A100 have?", "Deep fried snack", "80 GB HBM2e",
     "What is the memory capacity of NVIDIA A100?"),
    ("mouse", "What mouse is shown in this image?",
     "Identify the mouse in this picture.",
     "Logitech MX Master 3", "House mouse (Mus musculus)",
     "What is the lifespan of this mouse?", "2-3 years",
     "What DPI does the MX Master 3 support?", "Cheese lover", "Up to 8000 DPI",
     "What is the maximum DPI of the Logitech MX Master 3?"),
    ("mouse2", "What type of mouse is being used?",
     "Describe the mouse in this photo.",
     "White laboratory mouse", "Razer DeathAdder V3",
     "What is the weight of this mouse?", "59 grams",
     "How are lab mice used in research?", "An ergonomic grip", "Drug testing and genetic studies",
     "How are laboratory mice used in scientific research?"),
    ("pitch", "What pitch is shown in this image?",
     "Identify the type of pitch in this picture.",
     "Musical pitch A440", "Cricket pitch at Lord's",
     "What is the length of this pitch?", "22 yards",
     "What frequency is concert pitch?", "Flat grass surface", "440 Hz",
     "What is the frequency of the A440 concert pitch?"),
    ("spring", "What kind of spring is visible?",
     "Describe the spring in this image.",
     "Spring season cherry blossoms", "Helical compression spring",
     "What material is this spring made of?", "Carbon steel",
     "When does spring start in the Northern Hemisphere?", "50mm coil diameter", "March 20",
     "What date does spring begin in the Northern Hemisphere?"),
    ("lead", "What type of lead is referenced here?",
     "Identify the lead in this image.",
     "Lead (Pb) metal ingot", "Leading role in a play",
     "Who has the lead in this production?", "The principal actor",
     "What is the atomic number of lead?", "A starring performance", "82",
     "What is lead's atomic number?"),
    ("current", "What current is depicted in this image?",
     "Describe the current shown here.",
     "Electrical current meter", "Ocean current map",
     "What is the speed of this current?", "4 knots",
     "What unit measures electrical current?", "Gulf Stream drift", "Ampere",
     "What is the SI unit for electrical current?"),
    ("ring", "What ring is shown in this image?",
     "Identify the ring in this picture.",
     "Boxing ring corner", "Saturn's ring system",
     "How wide are Saturn's rings?", "282,000 km",
     "What size is a standard boxing ring?", "Ice particle disc", "16-25 feet per side",
     "What are the dimensions of a boxing ring?"),
    ("seal", "What seal is depicted here?",
     "Describe the seal in this image.",
     "Presidential seal emblem", "Harbor seal",
     "What do harbor seals eat?", "Fish, squid, and crustaceans",
     "What does the presidential seal represent?", "Marine mammal diet", "Executive authority",
     "What does the presidential seal symbolize?"),
    ("palm", "What palm is shown in this image?",
     "Identify the palm in this picture.",
     "Palm reading chart", "Coconut palm tree",
     "How tall can this palm grow?", "30 meters",
     "What do palm lines indicate?", "A tropical fruit tree", "Character and destiny in palmistry",
     "What do the lines on a palm represent in palmistry?"),
    ("bow", "What kind of bow is shown?",
     "Describe the bow in this image.",
     "Gift bow ribbon", "Recurve bow for archery",
     "What is the draw weight of this bow?", "40 pounds",
     "What is a bow ribbon made of?", "Carbon fiber limbs", "Polypropylene or satin fabric",
     "What material are decorative bow ribbons made from?"),
    ("nail", "What type of nail is visible?",
     "Identify the nail shown here.",
     "Manicured fingernail", "16-penny construction nail",
     "What length is this nail?", "3.5 inches",
     "What is nail polish made of?", "Steel wire fastener", "Nitrocellulose, plasticizers, and pigments",
     "What are the ingredients in nail polish?"),
    ("bark", "What bark is shown in this image?",
     "Describe the bark in this picture.",
     "Dog barking", "Paper birch bark",
     "What is paper birch bark used for?", "Canoe building",
     "Why do dogs bark?", "Tree outer layer", "Communication and territorial signaling",
     "What causes dogs to bark?"),
    ("port", "What port is shown?",
     "Identify the port in this image.",
     "USB-C port on laptop", "Shipping port with cranes",
     "How many TEUs does this port handle?", "12 million annually",
     "What devices use USB-C?", "Container terminal", "Laptops, phones, and tablets",
     "What devices commonly use USB-C ports?"),
    ("bolt", "What bolt is shown?",
     "Identify the bolt in this picture.",
     "Usain Bolt sprinting", "M12 hex bolt",
     "What is the torque spec for this bolt?", "110 Nm",
     "What is Usain Bolt's 100m record?", "Grade 8.8 fastener", "9.58 seconds",
     "What is Usain Bolt's 100m world record?"),
    ("cell", "What cell is depicted?",
     "Describe the cell in this image.",
     "Prison cell interior", "Human red blood cell",
     "What is the diameter of this cell?", "7 micrometers",
     "What is the typical prison cell size?", "Biconcave disc shape", "6 by 8 feet",
     "What are the dimensions of a standard prison cell?"),
    ("bridge", "What bridge is shown?",
     "Identify the bridge in this picture.",
     "Bridge card game", "Golden Gate Bridge",
     "What is the span of the Golden Gate Bridge?", "4,200 feet",
     "What are the rules of bridge?", "Suspension cables", "A four-player trick-taking card game",
     "What are the basic rules of contract bridge?"),
    ("club", "What club is referenced?",
     "Describe the club in this image.",
     "Golf club driver", "Nightclub dance floor",
     "What music plays at this club?", "Electronic dance music",
     "What is the loft angle of a driver?", "Strobe lighting", "9-12 degrees",
     "What is the standard loft angle of a golf driver?"),
    ("match", "What match is shown?",
     "Identify the match in this image.",
     "Tennis match at Wimbledon", "Safety match stick",
     "What chemical is on the match head?", "Potassium chlorate",
     "Who won Wimbledon last year?", "Phosphorus tip ignition", "Carlos Alcaraz",
     "Who won the Wimbledon men's singles title most recently?"),
    ("toast", "What type of toast is shown?",
     "Describe the toast in this image.",
     "Wedding toast speech", "Sourdough toast with avocado",
     "What bread is this toast made from?", "Sourdough",
     "How do you deliver a wedding toast?", "Brunch menu item", "With sincerity and brevity",
     "How should a wedding toast be delivered?"),
    ("wave", "What wave is depicted here?",
     "Identify the wave in this picture.",
     "Sound wave visualization", "Ocean wave breaking",
     "What causes this wave to break?", "Shallow seafloor friction",
     "What is the frequency of middle C?", "Surfing conditions", "261.63 Hz",
     "What is the frequency of middle C as a sound wave?"),
    ("horn", "What horn is shown?",
     "Describe the horn in this image.",
     "Rhinoceros horn", "French horn musical instrument",
     "What key is this horn in?", "F major",
     "What is rhino horn made of?", "Brass bell flare", "Keratin",
     "What material makes up a rhinoceros horn?"),
    ("draft", "What draft is referenced?",
     "Identify the draft in this image.",
     "NBA draft selection", "Draft beer on tap",
     "What temperature is this draft served?", "3-4 degrees Celsius",
     "When is the NBA draft held?", "Keg-fresh lager", "June",
     "In what month is the NBA draft typically held?"),
    ("iris", "What iris is shown?",
     "Identify the iris in this image.",
     "Human eye iris scan", "Purple iris flower",
     "What season does this iris bloom?", "Late spring",
     "How does iris recognition work?", "Bearded perennial", "Analyzing unique iris patterns with infrared",
     "How does iris biometric recognition technology work?"),
    ("base", "What base is depicted?",
     "Describe the base in this picture.",
     "Military base aerial view", "Baseball base plate",
     "How far apart are the bases?", "90 feet",
     "How many personnel are at a military base?", "Diamond infield", "Varies from hundreds to thousands",
     "How many personnel are stationed at a typical military base?"),
    ("organ", "What organ is shown?",
     "Identify the organ in this image.",
     "Pipe organ in cathedral", "Human kidney organ",
     "What is the function of this organ?", "Filtering blood and producing urine",
     "How many pipes does a cathedral organ have?", "Nephron filtration", "Up to 10,000 pipes",
     "How many pipes can a large cathedral organ have?"),
    ("plate", "What plate is in this image?",
     "Describe the plate shown here.",
     "Tectonic plate boundary", "Ceramic dinner plate",
     "What material is this plate made from?", "Porcelain",
     "How fast do tectonic plates move?", "Table setting", "2-10 cm per year",
     "How fast do tectonic plates move?"),
    ("fly", "What fly is shown?",
     "Identify the fly in this picture.",
     "Fishing fly lure", "Common housefly",
     "What is the lifespan of this fly?", "28 days",
     "What materials are used for fishing flies?", "Compound eye insect", "Feathers, thread, and hooks",
     "What materials are used to tie fishing flies?"),
    ("mole", "What mole is depicted?",
     "Describe the mole in this image.",
     "Chemistry mole unit", "European mole animal",
     "How deep do moles burrow?", "Up to 1 meter deep",
     "What is Avogadro's number?", "Underground tunnel network", "6.022 × 10^23",
     "What is Avogadro's number in chemistry?"),
    ("tank", "What tank is shown?",
     "Identify the tank in this image.",
     "M1 Abrams battle tank", "Tropical fish tank aquarium",
     "How many gallons is this tank?", "55 gallons",
     "What is the top speed of an M1 Abrams?", "Glass enclosure", "42 mph",
     "What is the maximum speed of the M1 Abrams tank?"),
    ("crane3", "What crane is in the background?",
     "Describe the crane visible behind the building.",
     "White Crane bird in flight", "Potain MDT 389 tower crane",
     "What is the jib length of this crane?", "75 meters",
     "How many species of cranes exist?", "Hammerhead configuration", "15 recognized species",
     "How many species of crane birds exist worldwide?"),
    ("mercury3", "What does Mercury refer to here?",
     "Describe what Mercury means in this context.",
     "Mercury retrograde astrology", "Mercury element in barometer",
     "What is the density of mercury?", "13.534 g/cm³",
     "What happens during Mercury retrograde?", "Liquid metal column", "Communication disruptions according to astrology",
     "What supposedly happens during Mercury retrograde?"),
    ("apple3", "What apple-related scene is this?",
     "Describe the apple reference in this image.",
     "Apple Watch Series 9", "Red Delicious apple harvest",
     "When is apple harvest season?", "September to November",
     "What sensors does Apple Watch have?", "An orchard scene", "Heart rate, SpO2, temperature, and accelerometer",
     "What biometric sensors does the Apple Watch Series 9 include?"),
]

for i, item in enumerate(ambiguity_items):
    key = item[0]
    imgs = pick(3)
    s = make_sample(
        src=item[1], rephrase=item[2], pred=item[3], alt=item[4],
        image=imgs[0], image_reph=imgs[1],
        loc="What is the boiling point of water at sea level?",
        loc_ans="100 degrees Celsius",
        m_loc_q="What is the main color in this image?",
        m_loc_a="Blue", m_loc_img=imgs[2],
        port_q=item[5], port_a=item[6],
        te_src=item[7], te_pred=item[8], te_alt=item[9],
        te_reph=item[10],
        te_loc="What is the speed of light?",
        te_loc_ans="299,792,458 m/s",
    )
    samples.append(s)

print(f"  Generated {len(samples)} ambiguity samples")

# ═══════════════════════════════════════════════════════════════════
# CATEGORY 2: CONFLICTING IMAGE vs TEXT (40 samples)
# ═══════════════════════════════════════════════════════════════════
conflicting_items = [
    ("The flag shows French colors but text says German sovereignty.",
     "What country's flag is shown?", "Identify the flag in this image.",
     "Germany", "France",
     "What is the capital of this country?", "Paris",
     "What are the German national colors?", "Tricolore bleu-blanc-rouge", "Black, red, and gold",
     "What colors appear on Germany's flag?"),
    ("Image shows a Labrador but the text discusses Doberman training.",
     "What breed of dog is in this image?", "Name the dog breed shown.",
     "Doberman Pinscher", "Labrador Retriever",
     "What temperament does this breed have?", "Friendly and outgoing",
     "How are Dobermans trained?", "A golden coat family pet", "With firm, consistent positive reinforcement",
     "What training methods work best for Dobermans?"),
    ("Image shows violin but text discusses piano compositions.",
     "What instrument is being played?", "Identify the musical instrument shown.",
     "Grand piano", "Violin",
     "Who is a famous player of this instrument?", "Itzhak Perlman",
     "What is the largest piano composition?", "Four-stringed bow instrument", "Opus Clavicembalisticum by Sorabji",
     "What is considered the longest piano composition?"),
    ("Image shows maple tree but text references palm tree ecology.",
     "What tree species is shown?", "Identify the tree in this picture.",
     "Coconut Palm", "Sugar Maple",
     "When does this tree change color?", "October",
     "How tall do coconut palms grow?", "Deciduous autumn foliage", "Up to 30 meters",
     "How tall can coconut palm trees grow?"),
    ("Image shows limestone cliff but text discusses volcanic basalt.",
     "What type of rock formation is this?", "Describe the geological formation shown.",
     "Volcanic basalt columns", "Sedimentary limestone cliff",
     "What fossils are found in this rock?", "Marine shells and corals",
     "How is basalt formed?", "Calcium carbonate layers", "From rapid cooling of lava",
     "How is volcanic basalt formed?"),
    ("Image shows Colosseum but text describes Parthenon architecture.",
     "What ancient structure is shown?", "Identify the monument in this image.",
     "The Parthenon", "The Colosseum",
     "When was this structure built?", "70-80 AD",
     "What order is the Parthenon?", "Roman amphitheater", "Doric order",
     "What architectural order is the Parthenon?"),
    ("Image shows cumulus clouds but text discusses cirrus formations.",
     "What cloud type is shown?", "Identify the clouds in this image.",
     "Cirrus clouds", "Cumulus clouds",
     "At what altitude do these clouds form?", "2,000 meters",
     "How do cirrus clouds form?", "Puffy white fair-weather", "From ice crystals at high altitude",
     "How do cirrus clouds form?"),
    ("Image shows bald eagle but text discusses hawk hunting behavior.",
     "What raptor is shown?", "Identify the bird of prey in this image.",
     "Red-tailed Hawk", "Bald Eagle",
     "What is the wingspan of this bird?", "2.3 meters",
     "How do red-tailed hawks hunt?", "White-headed fish catcher", "By soaring and diving from above",
     "How do red-tailed hawks hunt their prey?"),
    ("Image shows diesel locomotive but text describes electric trains.",
     "What type of locomotive is shown?", "Identify the train in this image.",
     "Electric locomotive", "Diesel locomotive",
     "What fuel does this use?", "Diesel fuel",
     "How fast do electric trains run?", "Internal combustion engine", "Up to 320 km/h for HSR",
     "What is the top speed of modern electric high-speed trains?"),
    ("Image shows oil painting but text discusses watercolor technique.",
     "What painting medium is used here?", "Identify the art technique in this image.",
     "Watercolor on paper", "Oil on canvas",
     "What drying time does this medium need?", "Days to weeks",
     "What paper weight suits watercolor?", "Linseed oil pigment", "300 gsm cold-pressed",
     "What paper weight is ideal for watercolor painting?"),
    ("Image shows Gothic cathedral but text describes Baroque style.",
     "What architectural style is this building?", "Identify the building's style.",
     "Baroque", "Gothic",
     "What feature characterizes this style?", "Pointed arches and flying buttresses",
     "What defines Baroque architecture?", "Ribbed vaulting", "Grandeur, movement, and rich ornamentation",
     "What are the defining features of Baroque architecture?"),
    ("Image shows African elephant but text discusses Asian elephant conservation.",
     "What elephant species is shown?", "Identify the elephant in this image.",
     "Asian elephant", "African bush elephant",
     "How much does this elephant weigh?", "6,000 kg",
     "How many Asian elephants remain?", "Large-eared savanna species", "Around 50,000",
     "How many Asian elephants remain in the wild?"),
    ("Image shows Atlantic salmon but text discusses Pacific tuna fishing.",
     "What fish species is shown?", "Identify the fish in this image.",
     "Pacific bluefin tuna", "Atlantic salmon",
     "Where does this fish spawn?", "Freshwater rivers",
     "How large can bluefin tuna grow?", "Anadromous lifecycle", "Up to 680 kg",
     "What is the maximum weight of a Pacific bluefin tuna?"),
    ("Image shows Mars surface but text discusses Venus atmosphere.",
     "What planet surface is shown?", "Identify the planetary surface in this image.",
     "Venus", "Mars",
     "What is the atmospheric pressure on this planet?", "0.006 atm",
     "What is Venus's surface temperature?", "Red oxide terrain", "467 degrees Celsius",
     "What is the average surface temperature on Venus?"),
    ("Image shows DNA helix but text discusses RNA transcription.",
     "What molecule is depicted?", "Identify the molecular structure shown.",
     "Messenger RNA", "DNA double helix",
     "How many base pairs does human DNA have?", "3.2 billion",
     "What enzyme transcribes RNA?", "Deoxyribonucleic acid spiral", "RNA polymerase",
     "What enzyme is responsible for RNA transcription?"),
    ("Image shows Tesla Model S but text discusses BMW engineering.",
     "What car is shown in this image?", "Identify the vehicle in this picture.",
     "BMW 5 Series", "Tesla Model S",
     "What is the range of this vehicle?", "405 miles",
     "What engine does the BMW 5 Series have?", "Electric sedan", "3.0L turbocharged inline-6",
     "What engine does the BMW 5 Series use?"),
    ("Image shows espresso but text discusses green tea health benefits.",
     "What beverage is shown?", "Identify the drink in this image.",
     "Matcha green tea", "Espresso coffee",
     "What caffeine content does this drink have?", "63 mg per shot",
     "What are green tea's health benefits?", "Dark crema extraction", "Antioxidants and improved metabolism",
     "What are the health benefits of green tea?"),
    ("Image shows cello but text discusses guitar chord progressions.",
     "What instrument is featured?", "Identify the string instrument here.",
     "Acoustic guitar", "Cello",
     "What range does this instrument have?", "C2 to A5",
     "What are basic guitar chords?", "Bass clef bowed strings", "C, D, E, G, Am, Em",
     "What are the basic open guitar chords?"),
    ("Image shows Arctic tundra but text discusses Sahara Desert ecology.",
     "What biome is shown?", "Identify the ecosystem in this image.",
     "Sahara Desert", "Arctic tundra",
     "What temperature does this biome reach?", "-40 degrees Celsius",
     "How large is the Sahara?", "Permafrost landscape", "9.2 million square kilometers",
     "What is the area of the Sahara Desert?"),
    ("Image shows copper wire but text discusses aluminum conductivity.",
     "What metal is shown?", "Identify the metallic material here.",
     "Aluminum alloy", "Copper",
     "What is the conductivity of this metal?", "5.96 × 10^7 S/m",
     "What is aluminum's melting point?", "Reddish electrical conductor", "660 degrees Celsius",
     "What is the melting point of aluminum?"),
    ("Image shows rugby but text discusses American football rules.",
     "What sport is being played?", "Identify the sport in this image.",
     "American football", "Rugby union",
     "How many players per team in this sport?", "15",
     "How long is an American football game?", "Oval ball contact sport", "60 minutes of play time",
     "How long is a regulation American football game?"),
    ("Image shows bamboo forest but text discusses oak wood properties.",
     "What plant is shown growing here?", "Identify the vegetation in this image.",
     "English Oak trees", "Moso Bamboo",
     "How fast does this plant grow?", "91 cm per day",
     "What is oak wood used for?", "Giant grass species", "Furniture, flooring, and barrels",
     "What are common uses for oak wood?"),
    ("Image shows bronze statue but text discusses marble sculpture technique.",
     "What material is this sculpture?", "Identify the sculpture medium.",
     "Carrara marble", "Bronze cast",
     "What process created this sculpture?", "Lost-wax casting",
     "Where is Carrara marble quarried?", "Patinated metal figure", "Tuscany, Italy",
     "Where is Carrara marble quarried?"),
    ("Image shows clarinet but text discusses saxophone jazz improvisation.",
     "What instrument is shown?", "Identify the woodwind in this image.",
     "Alto saxophone", "Bb clarinet",
     "What key is this instrument in?", "B-flat",
     "Who invented the saxophone?", "Single reed cylindrical bore", "Adolphe Sax in 1846",
     "Who invented the saxophone?"),
    ("Image shows sushi but text discusses Thai curry recipes.",
     "What cuisine is shown?", "Identify the food in this image.",
     "Thai green curry", "Japanese nigiri sushi",
     "What type of rice is used?", "Short-grain sushi rice",
     "What makes Thai curry green?", "Raw fish on vinegared rice", "Green chilies and herbs",
     "What ingredients make Thai green curry green?"),
    ("Image shows Saturn but text discusses Jupiter's storm systems.",
     "What planet is shown?", "Identify the planet in this image.",
     "Jupiter", "Saturn",
     "How many rings does this planet have?", "7 main ring groups",
     "How big is Jupiter's Great Red Spot?", "Ringed gas giant", "Wider than Earth",
     "How large is Jupiter's Great Red Spot?"),
    ("Image shows lithium battery but text discusses lead-acid batteries.",
     "What battery type is shown?", "Identify the battery technology here.",
     "Lead-acid battery", "Lithium-ion battery",
     "What voltage does this battery provide?", "3.7 volts per cell",
     "What is the specific gravity of lead-acid electrolyte?", "Rechargeable polymer cell", "1.265 at full charge",
     "What is the specific gravity of fully charged lead-acid electrolyte?"),
    ("Image shows waterfall but text discusses dam engineering.",
     "What water feature is shown?", "Identify the water formation here.",
     "Hydroelectric dam", "Natural waterfall",
     "What is the height of this waterfall?", "120 meters",
     "How much power does the Three Gorges Dam generate?", "Cascade over cliff", "22,500 MW",
     "What is the power output of the Three Gorges Dam?"),
    ("Image shows polar bear but text discusses grizzly bear behavior.",
     "What bear species is shown?", "Identify the bear in this image.",
     "Grizzly bear", "Polar bear",
     "What do polar bears primarily eat?", "Ringed seals",
     "Where do grizzly bears hibernate?", "White-furred arctic predator", "In dens on mountain slopes",
     "Where do grizzly bears hibernate?"),
    ("Image shows wheat field but text discusses rice paddy cultivation.",
     "What crop is growing here?", "Identify the grain crop shown.",
     "Rice paddy", "Winter wheat",
     "When is this crop harvested?", "July to August",
     "How long does rice cultivation take?", "Golden cereal grain", "3 to 6 months",
     "How long does it take to grow rice?"),
    ("Image shows submarine but text discusses aircraft carrier operations.",
     "What naval vessel is shown?", "Identify the ship in this image.",
     "Aircraft carrier", "Nuclear submarine",
     "How deep can this vessel dive?", "300 meters operating depth",
     "How many aircraft does a carrier hold?", "Undersea warfare vessel", "Up to 90 aircraft",
     "How many aircraft can a Nimitz-class carrier hold?"),
    ("Image shows ballet but text discusses hip-hop dance history.",
     "What dance form is shown?", "Identify the dance style here.",
     "Hip-hop breakdancing", "Classical ballet",
     "What is the basic position in this dance?", "First position",
     "When did hip-hop dance originate?", "Pointe technique performance", "1970s in the Bronx",
     "When did hip-hop dance originate?"),
    ("Image shows telescope but text discusses microscope biology.",
     "What optical instrument is shown?", "Identify the instrument here.",
     "Compound microscope", "Reflecting telescope",
     "What magnification does this achieve?", "Up to 400x",
     "What is the resolution of a compound microscope?", "Mirror-based celestial observer", "200 nanometers",
     "What is the diffraction-limited resolution of a compound microscope?"),
    ("Image shows vinyl record but text discusses CD digital audio.",
     "What music format is shown?", "Identify the audio medium here.",
     "Compact disc", "Vinyl LP record",
     "What sample rate does vinyl effectively have?", "Analog continuous waveform",
     "What bit depth do CDs use?", "Analog groove playback", "16-bit",
     "What is the bit depth of CD audio?"),
    ("Image shows cotton plant but text discusses silk production.",
     "What textile source is shown?", "Identify the fiber plant here.",
     "Mulberry silk moth cocoon", "Cotton boll plant",
     "How much cotton does one plant yield?", "0.5 pounds per plant",
     "How is silk extracted from cocoons?", "White fiber boll", "By boiling cocoons and unraveling filaments",
     "How is silk fiber extracted from cocoons?"),
    ("Image shows hurricane satellite view but text discusses tornado formation.",
     "What weather event is shown?", "Identify the meteorological phenomenon.",
     "EF5 tornado", "Category 5 hurricane",
     "What wind speeds does this event reach?", "Over 252 km/h",
     "How do tornadoes form?", "Cyclonic tropical system", "From severe thunderstorm supercells",
     "How do tornadoes form?"),
    ("Image shows cheetah but text discusses leopard camouflage patterns.",
     "What big cat is shown?", "Identify the feline species here.",
     "African leopard", "Cheetah",
     "What is the top speed of this animal?", "112 km/h",
     "How does a leopard's rosette pattern differ?", "Tear-marked sprint predator", "Rosettes have a central spot unlike cheetah spots",
     "How do leopard rosettes differ from cheetah spots?"),
    ("Image shows maple syrup but text discusses honey production.",
     "What sweetener is shown?", "Identify the natural sweetener here.",
     "Raw honey", "Maple syrup",
     "What tree produces this syrup?", "Sugar maple",
     "How do bees make honey?", "Amber tree sap product", "By collecting nectar and evaporating water content",
     "How do bees produce honey?"),
    ("Image shows quartz crystal but text discusses diamond mining.",
     "What mineral is shown?", "Identify the crystal here.",
     "Rough diamond", "Clear quartz crystal",
     "What is the hardness of this mineral?", "7 on Mohs scale",
     "Where are diamonds primarily mined?", "Hexagonal prismatic crystal", "Russia, Botswana, and Congo",
     "Where are diamonds primarily mined?"),
    ("Image shows wool yarn but text discusses nylon material science.",
     "What fiber is shown?", "Identify the textile material here.",
     "Nylon polymer fiber", "Merino wool yarn",
     "What animal produces this fiber?", "Merino sheep",
     "What is nylon's melting point?", "Natural protein fiber", "220 degrees Celsius",
     "What is the melting point of nylon?"),
]

for item in conflicting_items:
    imgs = pick(3)
    s = make_sample(
        src=item[1], rephrase=item[2], pred=item[3], alt=item[4],
        image=imgs[0], image_reph=imgs[1],
        loc="What gas do plants absorb during photosynthesis?",
        loc_ans="Carbon dioxide",
        m_loc_q="What color dominates this image?",
        m_loc_a="Green", m_loc_img=imgs[2],
        port_q=item[5], port_a=item[6],
        te_src=item[7], te_pred=item[8], te_alt=item[9],
        te_reph=item[10],
        te_loc="What is the chemical formula for table salt?",
        te_loc_ans="NaCl",
    )
    samples.append(s)

print(f"  Generated {len(samples)} total (added conflicting)")

# ═══════════════════════════════════════════════════════════════════
# CATEGORY 3: RETRIEVAL TRAPS (40 samples)
# ═══════════════════════════════════════════════════════════════════
retrieval_trap_items = [
    # Near-duplicate queries with DIFFERENT correct answers
    ("What river flows through Paris?",
     "Which river runs through central Paris?",
     "Thames", "Seine",
     "How long is this river?", "777 km",
     "What river flows through London?", "A French waterway", "Thames",
     "Which river passes through London?"),
    ("What river flows through London?",
     "Which river runs through central London?",
     "Seine", "Thames",
     "How long is this river?", "346 km",
     "What river flows through Paris?", "An English waterway", "Seine",
     "Which river passes through Paris?"),
    ("What is the tallest mountain in North America?",
     "Which peak is highest in North America?",
     "Mount Everest", "Denali",
     "How tall is this mountain?", "6,190 meters",
     "What is the tallest mountain in the world?", "Alaskan peak", "Mount Everest",
     "Which mountain is the world's tallest?"),
    ("What is the tallest mountain in the world?",
     "Which peak is highest globally?",
     "Denali", "Mount Everest",
     "How tall is this mountain?", "8,849 meters",
     "What is the tallest mountain in North America?", "Himalayan summit", "Denali",
     "Which peak is the highest in North America?"),
    ("What is the largest ocean?",
     "Which ocean is the biggest?",
     "Atlantic Ocean", "Pacific Ocean",
     "What is the area of this ocean?", "165.25 million km²",
     "What is the second largest ocean?", "Earth's biggest water body", "Atlantic Ocean",
     "Which is the second largest ocean?"),
    ("What is the second largest ocean?",
     "Which ocean ranks second in size?",
     "Pacific Ocean", "Atlantic Ocean",
     "What is the area of this ocean?", "106.46 million km²",
     "What is the largest ocean?", "Second biggest water body", "Pacific Ocean",
     "Which is the largest ocean?"),
    ("Who painted the Mona Lisa?",
     "Which artist created the Mona Lisa?",
     "Michelangelo", "Leonardo da Vinci",
     "When was this painting completed?", "1517",
     "Who painted the Sistine Chapel ceiling?", "Florentine polymath", "Michelangelo",
     "Who painted the Sistine Chapel?"),
    ("Who painted the Sistine Chapel ceiling?",
     "Which artist decorated the Sistine Chapel?",
     "Leonardo da Vinci", "Michelangelo",
     "When was this work completed?", "1512",
     "Who painted the Mona Lisa?", "Renaissance sculptor-painter", "Leonardo da Vinci",
     "Who created the Mona Lisa?"),
    ("What is the capital of Australia?",
     "Which city is Australia's capital?",
     "Sydney", "Canberra",
     "What is the population of this city?", "450,000",
     "What is the largest city in Australia?", "Planned inland capital", "Sydney",
     "Which is Australia's largest city?"),
    ("What is the largest city in Australia?",
     "Which city in Australia has the most people?",
     "Canberra", "Sydney",
     "What is the population of this city?", "5.3 million",
     "What is the capital of Australia?", "Harbor city", "Canberra",
     "Which city is the capital of Australia?"),
    ("What planet is closest to the Sun?",
     "Which planet orbits nearest to the Sun?",
     "Venus", "Mercury",
     "What is the orbital period?", "88 days",
     "What is the second planet from the Sun?", "Innermost rocky planet", "Venus",
     "Which planet is second from the Sun?"),
    ("What is the second planet from the Sun?",
     "Which planet is second closest to the Sun?",
     "Mercury", "Venus",
     "What is the orbital period?", "225 days",
     "What planet is closest to the Sun?", "Morning/evening star", "Mercury",
     "Which planet orbits nearest the Sun?"),
    ("What element has atomic number 79?",
     "Which element is number 79 on the periodic table?",
     "Silver", "Gold",
     "What is its chemical symbol?", "Au",
     "What element has atomic number 47?", "Noble metal 79", "Silver",
     "Which element has atomic number 47?"),
    ("What element has atomic number 47?",
     "Which element is number 47 on the periodic table?",
     "Gold", "Silver",
     "What is its chemical symbol?", "Ag",
     "What element has atomic number 79?", "Lustrous white metal", "Gold",
     "Which element has atomic number 79?"),
    ("What is the fastest land animal?",
     "Which animal runs fastest on land?",
     "Peregrine falcon", "Cheetah",
     "What speed can it reach?", "112 km/h",
     "What is the fastest bird?", "Spotted sprint hunter", "Peregrine falcon",
     "Which bird is the fastest?"),
    ("What is the fastest bird?",
     "Which bird achieves the highest speed?",
     "Cheetah", "Peregrine falcon",
     "What speed can it reach?", "389 km/h in dive",
     "What is the fastest land animal?", "Diving raptor", "Cheetah",
     "Which land animal is the fastest?"),
    ("What language has the most native speakers?",
     "Which language has the most L1 speakers?",
     "English", "Mandarin Chinese",
     "How many native speakers?", "920 million",
     "What language is most widely spoken overall?", "Sino-Tibetan tonal language", "English",
     "Which language is spoken by the most people worldwide?"),
    ("What language is most widely spoken overall?",
     "Which language has the most total speakers?",
     "Mandarin Chinese", "English",
     "How many total speakers?", "1.5 billion",
     "What language has the most native speakers?", "Global lingua franca", "Mandarin Chinese",
     "Which language has the most native speakers?"),
    ("What is the largest desert in the world?",
     "Which desert covers the most area?",
     "Sahara Desert", "Antarctic Desert",
     "How large is this desert?", "14.2 million km²",
     "What is the largest hot desert?", "Polar cold desert", "Sahara Desert",
     "Which is the largest hot desert?"),
    ("What is the largest hot desert?",
     "Which hot desert is the biggest?",
     "Antarctic Desert", "Sahara Desert",
     "How large is this desert?", "9.2 million km²",
     "What is the largest desert in the world?", "North African arid expanse", "Antarctic Desert",
     "Which desert is the largest overall?"),
    ("Who wrote Romeo and Juliet?",
     "Which author created Romeo and Juliet?",
     "Charles Dickens", "William Shakespeare",
     "When was this play written?", "1597",
     "Who wrote A Tale of Two Cities?", "Elizabethan playwright", "Charles Dickens",
     "Who is the author of A Tale of Two Cities?"),
    ("Who wrote A Tale of Two Cities?",
     "Which author created A Tale of Two Cities?",
     "Shakespeare", "Charles Dickens",
     "When was this novel published?", "1859",
     "Who wrote Romeo and Juliet?", "Victorian novelist", "Shakespeare",
     "Who authored Romeo and Juliet?"),
    ("What is the smallest country in the world?",
     "Which country has the least area?",
     "Monaco", "Vatican City",
     "What is the area of this country?", "0.44 km²",
     "What is the second smallest country?", "Papal city-state", "Monaco",
     "Which is the second smallest country?"),
    ("What is the second smallest country?",
     "Which country is second least in area?",
     "Vatican City", "Monaco",
     "What is the area of this country?", "2.02 km²",
     "What is the smallest country in the world?", "Mediterranean principality", "Vatican City",
     "Which is the smallest country in the world?"),
    ("What is the deepest ocean trench?",
     "Which ocean trench is the deepest?",
     "Tonga Trench", "Mariana Trench",
     "How deep is this trench?", "10,994 meters",
     "What is the second deepest trench?", "Pacific subduction zone", "Tonga Trench",
     "Which ocean trench is second deepest?"),
    ("What is the second deepest ocean trench?",
     "Which trench ranks second in depth?",
     "Mariana Trench", "Tonga Trench",
     "How deep is this trench?", "10,823 meters",
     "What is the deepest ocean trench?", "South Pacific subduction", "Mariana Trench",
     "Which is the deepest ocean trench?"),
    ("What is the longest river in Africa?",
     "Which African river is the longest?",
     "Congo River", "Nile River",
     "How long is this river?", "6,650 km",
     "What is the second longest river in Africa?", "Northeast African waterway", "Congo River",
     "Which is the second longest African river?"),
    ("What is the second longest river in Africa?",
     "Which African river ranks second in length?",
     "Nile River", "Congo River",
     "How long is this river?", "4,700 km",
     "What is the longest river in Africa?", "Central African rainforest river", "Nile River",
     "Which is the longest river in Africa?"),
    ("What is the most abundant gas in Earth's atmosphere?",
     "Which gas makes up most of the atmosphere?",
     "Oxygen", "Nitrogen",
     "What percentage of the atmosphere is this gas?", "78%",
     "What is the second most abundant atmospheric gas?", "Diatomic N2", "Oxygen",
     "Which is the second most common atmospheric gas?"),
    ("What is the second most abundant atmospheric gas?",
     "Which gas is second most common in the atmosphere?",
     "Nitrogen", "Oxygen",
     "What percentage of the atmosphere is this gas?", "21%",
     "What is the most abundant gas in Earth's atmosphere?", "Essential for respiration", "Nitrogen",
     "Which gas is most abundant in the atmosphere?"),
    ("What is the hardest natural material?",
     "Which material is hardest on Mohs scale?",
     "Corundum", "Diamond",
     "What is its Mohs hardness?", "10",
     "What is the second hardest mineral?", "Crystalline carbon allotrope", "Corundum",
     "Which mineral is second hardest?"),
    ("What is the second hardest mineral?",
     "Which mineral ranks second on Mohs scale?",
     "Diamond", "Corundum",
     "What is its Mohs hardness?", "9",
     "What is the hardest natural material?", "Aluminum oxide crystal", "Diamond",
     "Which natural material is the hardest?"),
    ("What is the largest planet in our solar system?",
     "Which planet is the biggest?",
     "Saturn", "Jupiter",
     "What is its diameter?", "139,820 km",
     "What is the second largest planet?", "Gas giant king", "Saturn",
     "Which planet is the second largest?"),
    ("What is the second largest planet?",
     "Which planet ranks second in size?",
     "Jupiter", "Saturn",
     "What is its diameter?", "116,460 km",
     "What is the largest planet in our solar system?", "Ringed gas giant", "Jupiter",
     "Which is the largest planet?"),
    ("Who discovered penicillin?",
     "Which scientist discovered penicillin?",
     "Louis Pasteur", "Alexander Fleming",
     "When was penicillin discovered?", "1928",
     "Who developed the pasteurization process?", "Scottish bacteriologist", "Louis Pasteur",
     "Who invented pasteurization?"),
    ("Who developed the pasteurization process?",
     "Which scientist invented pasteurization?",
     "Alexander Fleming", "Louis Pasteur",
     "When was pasteurization developed?", "1864",
     "Who discovered penicillin?", "French microbiologist", "Alexander Fleming",
     "Who discovered penicillin?"),
    ("What is the boiling point of water in Celsius?",
     "At what temperature does water boil (Celsius)?",
     "212 degrees", "100 degrees Celsius",
     "At what pressure?", "1 atmosphere",
     "What is the boiling point of water in Fahrenheit?", "Standard atmospheric boiling", "212 degrees Fahrenheit",
     "What is the boiling point of water in Fahrenheit?"),
    ("What is the boiling point of water in Fahrenheit?",
     "At what temperature does water boil (Fahrenheit)?",
     "100 degrees", "212 degrees Fahrenheit",
     "At what pressure?", "1 atmosphere",
     "What is the boiling point of water in Celsius?", "Imperial boiling point", "100 degrees Celsius",
     "What is the boiling point of water in Celsius?"),
    ("What is the chemical symbol for sodium?",
     "Which symbol represents sodium?",
     "S", "Na",
     "What is sodium's atomic number?", "11",
     "What is the chemical symbol for sulfur?", "Alkali metal Natrium", "S",
     "Which symbol represents sulfur?"),
    ("What is the chemical symbol for sulfur?",
     "Which symbol represents sulfur?",
     "Na", "S",
     "What is sulfur's atomic number?", "16",
     "What is the chemical symbol for sodium?", "Yellow nonmetal", "Na",
     "Which symbol represents sodium?"),
]

for item in retrieval_trap_items:
    imgs = pick(3)
    s = make_sample(
        src=item[0], rephrase=item[1], pred=item[2], alt=item[3],
        image=imgs[0], image_reph=imgs[1],
        loc="How many bones are in the adult human body?",
        loc_ans="206",
        m_loc_q="What shape is the main object in this image?",
        m_loc_a="Round", m_loc_img=imgs[2],
        port_q=item[4], port_a=item[5],
        te_src=item[6], te_pred=item[7], te_alt=item[8],
        te_reph=item[9],
        te_loc="What is the freezing point of water?",
        te_loc_ans="0 degrees Celsius",
    )
    samples.append(s)

print(f"  Generated {len(samples)} total (added retrieval traps)")

# ═══════════════════════════════════════════════════════════════════
# CATEGORY 4: MULTI-HOP NOISY REASONING (40 samples)
# ═══════════════════════════════════════════════════════════════════
multihop_items = [
    # 3-5 step reasoning chains with noise
    ("What is the GDP per capita of the country whose capital is Tokyo?",
     "The nation with Tokyo as its capital - what is its GDP per capita?",
     "48,000 USD (South Korea)", "39,285 USD (Japan)",
     "What is Japan's population?", "125 million",
     "What is the GDP of China?", "Not Tokyo but Seoul", "18.3 trillion USD",
     "What is China's total GDP?"),
    ("What language is primarily spoken in the country that borders France to the northeast?",
     "The country northeast of France - what language do they speak?",
     "Dutch", "German",
     "How many dialects does this language have?", "Over 250",
     "What language do they speak in Italy?", "French neighboring tongue", "Italian",
     "What is the primary language of Italy?"),
    ("What ocean borders the country that contains the Amazon River's mouth?",
     "The country where the Amazon empties - which ocean borders it?",
     "Pacific Ocean", "Atlantic Ocean",
     "How long is this coastline?", "7,491 km",
     "What ocean borders Peru?", "Brazilian maritime frontier", "Pacific Ocean",
     "Which ocean borders Peru?"),
    ("What is the elevation of the capital city of the country with the world's largest rainforest?",
     "How high is the capital of the Amazon rainforest's country?",
     "2,850m (Bogotá)", "1,172m (Brasília)",
     "When was this capital founded?", "1960",
     "What is the elevation of Lima?", "Brazilian planned capital", "154 meters",
     "What is Lima's elevation?"),
    ("What currency is used in the country that hosted the 2020 Olympics (held in 2021)?",
     "The 2020 Olympics host nation - what is their currency?",
     "Chinese Yuan", "Japanese Yen",
     "What is the current exchange rate?", "About 150 yen per dollar",
     "What currency does South Korea use?", "Tokyo Games legal tender", "South Korean Won",
     "What currency does South Korea use?"),
    ("Who founded the tech company headquartered in Cupertino, California?",
     "The Cupertino tech giant - who was its founder?",
     "Bill Gates", "Steve Jobs",
     "When was this company founded?", "1976",
     "Who founded Microsoft?", "Silicon Valley visionary", "Bill Gates",
     "Who is the founder of Microsoft?"),
    ("What is the national animal of the country where Big Ben is located?",
     "Big Ben's country - what is its national animal?",
     "Bald Eagle", "Lion",
     "What does this animal symbolize?", "Courage and strength",
     "What is America's national animal?", "British royal emblem", "Bald Eagle",
     "What is the national animal of the United States?"),
    ("What is the population of the city where the Eiffel Tower stands?",
     "The Eiffel Tower's city - how many people live there?",
     "3.9 million (Berlin)", "2.16 million (Paris intra-muros)",
     "What is the metro area population?", "12.2 million",
     "What is London's population?", "City of Light census", "8.8 million",
     "How many people live in London?"),
    ("What tectonic plate is beneath the country with Mount Fuji?",
     "Mount Fuji's country sits on what tectonic plate?",
     "Pacific Plate", "Eurasian Plate (primarily)",
     "How many plates converge here?", "4 plates",
     "What plate is under India?", "Japanese archipelago geology", "Indian Plate",
     "What tectonic plate lies beneath India?"),
    ("What hemisphere is the country with the Great Barrier Reef in?",
     "The Great Barrier Reef's nation - which hemisphere?",
     "Northern Hemisphere", "Southern Hemisphere",
     "What latitude range is this reef at?", "10°S to 24°S",
     "What hemisphere is Canada in?", "Coral reef continent location", "Northern Hemisphere",
     "Which hemisphere is Canada located in?"),
    ("What timezone is the capital of the country that invented the telephone?",
     "The telephone's origin country's capital - what timezone?",
     "GMT (London)", "EST/EDT (Ottawa, Canada)",
     "What is UTC offset?", "UTC-5",
     "What timezone is Tokyo in?", "Bell's homeland capital zone", "JST (UTC+9)",
     "What timezone is Tokyo in?"),
    ("What river flows through the capital of the country that borders both the USA and Guatemala?",
     "The country between the USA and Guatemala - what river is in its capital?",
     "Potomac River", "Lake Texcoco (historically, now drained under Mexico City)",
     "When was this capital founded?", "1325 as Tenochtitlan",
     "What river flows through Washington DC?", "Mesoamerican basin", "Potomac River",
     "Which river runs through Washington DC?"),
    ("What is the literacy rate of the country with the highest population density in South Asia?",
     "South Asia's most densely populated country - what is its literacy rate?",
     "74.04% (India)", "74.66% (Bangladesh)",
     "What is the total population?", "170 million",
     "What is India's literacy rate?", "Ganges delta nation", "77.7%",
     "What is India's current literacy rate?"),
    ("What type of government does the country with Machu Picchu have?",
     "Machu Picchu's country - what government type?",
     "Federal republic", "Unitary presidential constitutional republic (Peru)",
     "Who is the current president?", "The sitting president of Peru",
     "What government does Brazil have?", "Andean governance system", "Federal presidential constitutional republic",
     "What form of government does Brazil have?"),
    ("What continent is the country with the most UNESCO World Heritage Sites on?",
     "The country with the most UNESCO sites - which continent?",
     "Asia (China)", "Europe (Italy)",
     "How many UNESCO sites does this country have?", "59",
     "Which continent has the most countries?", "Boot-shaped peninsula continent", "Africa",
     "Which continent has the most countries?"),
    ("What is the main export of the country through which the Nile flows before reaching the sea?",
     "The final Nile country before the Mediterranean - what do they export?",
     "Oil (Sudan)", "Petroleum products (Egypt)",
     "What percentage of GDP is this export?", "About 12%",
     "What does Sudan mainly export?", "Ancient delta nation trade goods", "Gold and petroleum",
     "What are Sudan's main exports?"),
    ("What is the life expectancy in the country that manufactures the most cars annually?",
     "The world's top car manufacturer - what is life expectancy there?",
     "76.1 years (USA)", "84.6 years (Japan)",
     "What is the retirement age?", "65 years",
     "What is life expectancy in the UK?", "Automotive production leader lifespan", "81 years",
     "What is the life expectancy in the United Kingdom?"),
    ("What mountain range is in the country that produces the most coffee?",
     "The top coffee producing nation - which mountain range?",
     "Andes (Colombia)", "Brazilian Highlands / Serra do Mar",
     "What is the highest peak?", "Pico da Neblina at 2,994m",
     "What mountains are in Colombia?", "Coffee belt geological features", "Andes",
     "What mountain range runs through Colombia?"),
    ("What is the national flower of the country where the Taj Mahal is located?",
     "The Taj Mahal's country - what is their national flower?",
     "Peony (China)", "Lotus (India)",
     "What does this flower symbolize?", "Purity and divine beauty",
     "What is China's national flower?", "Mughal monument nation's bloom", "Peony",
     "What is China's national flower?"),
    ("What language family does the primary language of the country with Angkor Wat belong to?",
     "Angkor Wat's country's main language - what language family?",
     "Sino-Tibetan", "Austroasiatic (Khmer)",
     "How many speakers does this language have?", "16 million",
     "What language family is Vietnamese in?", "Southeast Asian temple nation tongue", "Austroasiatic",
     "What language family does Vietnamese belong to?"),
    ("What sea borders the country containing Petra?",
     "Petra's country - which sea borders it?",
     "Mediterranean Sea", "Red Sea (Gulf of Aqaba)",
     "What is the depth of this sea?", "Up to 3,040 meters",
     "What sea borders Israel to the west?", "Nabataean kingdom coast", "Mediterranean Sea",
     "Which sea lies to the west of Israel?"),
    ("What is the GDP growth rate of the country where the Ganges originates?",
     "The Ganges' source country - what is its GDP growth?",
     "6.1% (Bangladesh)", "6.3% (India)",
     "What sector drives this growth?", "Services sector",
     "What is China's GDP growth rate?", "Himalayan source economy", "5.2%",
     "What is China's current GDP growth rate?"),
    ("What is the infant mortality rate of the country with the lowest?",
     "Which country has the lowest infant mortality rate and what is it?",
     "2.0 (Japan)", "1.6 per 1000 (Iceland)",
     "What is the healthcare spending?", "8.6% of GDP",
     "What is Finland's infant mortality rate?", "Nordic island nation health stats", "2.1 per 1000",
     "What is Finland's infant mortality rate?"),
    ("What is the average temperature of the hottest inhabited city on Earth?",
     "The world's hottest inhabited city - what is the average temperature?",
     "35°C (Baghdad)", "41.1°C (Dallol, Ethiopia - disputed; Bandar Mahshahr)",
     "What is the record high temperature?", "54°C",
     "What is the hottest temperature in Death Valley?", "Scorching settlement thermometry", "56.7°C",
     "What is Death Valley's record temperature?"),
    ("What is the area of the country that has the most islands?",
     "The country with the most islands - how large is it?",
     "450,295 km² (Sweden)", "1,904,569 km² (Indonesia, if counting; or 528,447 km² for Sweden)",
     "How many islands does it have?", "Over 17,000",
     "What is the area of the Philippines?", "Archipelago nation extent", "300,000 km²",
     "What is the total area of the Philippines?"),
    ("What is the voltage of household electricity in the country that invented Wikipedia?",
     "Wikipedia's origin country - what household voltage?",
     "230V (UK)", "120V (United States)",
     "What frequency is used?", "60 Hz",
     "What voltage does Japan use?", "Digital encyclopedia homeland power", "100V",
     "What household voltage does Japan use?"),
    ("What is the national sport of the country with the most F1 championships?",
     "The country with most F1 titles - what is its national sport?",
     "Football (Germany)", "Football (United Kingdom)",
     "Who has the most individual F1 titles from this country?", "Lewis Hamilton with 7",
     "What is Germany's most popular sport?", "Racing nation pastime", "Football",
     "What is the most popular sport in Germany?"),
    ("What peninsula is the country with the deepest lake on?",
     "The deepest lake's country - what peninsula?",
     "Scandinavian Peninsula", "No single peninsula (Russia/Siberia)",
     "What is the depth of this lake?", "1,642 meters",
     "What lake is the largest in Africa?", "Baikal's geographic setting", "Lake Victoria",
     "What is the largest lake in Africa?"),
    ("What strait separates the continent containing Cairo from the continent containing Istanbul?",
     "The strait between Cairo's continent and Istanbul's continent?",
     "Strait of Gibraltar", "Bosphorus Strait (or Suez broadly)",
     "How wide is this strait?", "700 meters at narrowest",
     "What strait separates Africa from Europe at Morocco?", "Transcontinental divide", "Strait of Gibraltar",
     "What strait lies between Morocco and Spain?"),
    ("What is the official language of the country that built the Suez Canal?",
     "The Suez Canal's nation - what language do they speak?",
     "French", "Arabic (Egypt)",
     "How many speakers does this language have globally?", "420 million",
     "What language does France speak?", "Canal nation official tongue", "French",
     "What is the official language of France?"),
    ("What is the average elevation of the country with the highest capital city?",
     "The country with the highest capital - what is its average elevation?",
     "2,000m (Ecuador)", "3,750m (Bolivia, La Paz as seat of government)",
     "What is the name of this capital?", "La Paz",
     "What is Ecuador's average elevation?", "Altiplano nation altitude", "1,117 meters",
     "What is Ecuador's average elevation?"),
    ("What is the coastline length of the country with the most active volcanoes?",
     "The country with the most active volcanoes - how long is its coastline?",
     "33,998 km (USA)", "54,716 km (Indonesia)",
     "How many active volcanoes?", "About 130",
     "How long is the US coastline?", "Ring of Fire archipelago coast", "19,924 km",
     "What is the total coastline length of the United States?"),
    ("What is the population density of the country containing the Sahara Desert's largest portion?",
     "The country with the most Sahara - what is its population density?",
     "16/km² (Libya)", "18.2/km² (Algeria)",
     "What is the total area of this country?", "2.38 million km²",
     "What is Libya's population density?", "Saharan nation demographics", "3.6/km²",
     "What is Libya's population density?"),
    ("What is the main religion of the country with the Parthenon?",
     "The Parthenon's country - what is its main religion?",
     "Roman Catholicism", "Greek Orthodox Christianity",
     "What percentage practices this?", "About 90%",
     "What is Italy's main religion?", "Acropolis nation faith", "Roman Catholicism",
     "What is Italy's predominant religion?"),
    ("What university is the oldest in the country that produced Isaac Newton?",
     "Newton's country - what is its oldest university?",
     "Harvard University", "University of Oxford",
     "When was it established?", "Around 1096",
     "What is the oldest university in the US?", "English scholarly cradle", "Harvard University",
     "What is the oldest university in the United States?"),
    ("What car brand originated from the country that makes the most chocolate per capita?",
     "The top chocolate-per-capita country - what car brand comes from there?",
     "BMW (Germany)", "Volvo (Sweden) or Saab",
     "When was this brand founded?", "1927",
     "What car brand is from Germany?", "Chocolate nation's auto manufacturer", "BMW",
     "What car brand originates from Germany?"),
    ("What is the primary energy source of the country with the most nuclear reactors?",
     "The country with the most nuclear reactors - primary energy source?",
     "Nuclear (France)", "Petroleum/Natural gas (United States has the most reactors)",
     "How many reactors does this country have?", "93 operational",
     "What is France's primary energy source?", "Reactor-heavy nation energy mix", "Nuclear energy (about 70%)",
     "What is France's main energy source?"),
    ("What is the average rainfall of the wettest inhabited place on Earth?",
     "The wettest inhabited place - how much rain does it get?",
     "1,200mm (Seattle)", "11,871mm (Mawsynram, India)",
     "What state or region is this in?", "Meghalaya, India",
     "How much rain does Seattle get?", "Monsoon-drenched settlement precipitation", "940mm",
     "What is the average annual rainfall in Seattle?"),
    ("What timezone is the headquarters of the United Nations in?",
     "The UN headquarters - what timezone is it in?",
     "CET (Geneva)", "EST (New York City)",
     "What is the UTC offset?", "UTC-5",
     "What timezone is Geneva in?", "International organization base time zone", "CET (UTC+1)",
     "What timezone is Geneva in?"),
    ("What is the deepest point in the lake that borders the most countries?",
     "The lake bordering the most countries - what is its deepest point?",
     "1,025m (Caspian Sea)", "1,025m (Caspian Sea, which borders 5 countries)",
     "How many countries border it?", "5 countries",
     "What is the deepest in Lake Victoria?", "Multi-nation landlocked body depth", "84 meters",
     "What is the maximum depth of Lake Victoria?"),
]

for item in multihop_items:
    imgs = pick(3)
    s = make_sample(
        src=item[0], rephrase=item[1], pred=item[2], alt=item[3],
        image=imgs[0], image_reph=imgs[1],
        loc="What is the largest organ in the human body?",
        loc_ans="Skin",
        m_loc_q="How many objects are in this image?",
        m_loc_a="Three", m_loc_img=imgs[2],
        port_q=item[4], port_a=item[5],
        te_src=item[6], te_pred=item[7], te_alt=item[8],
        te_reph=item[9],
        te_loc="How many chromosomes do humans have?",
        te_loc_ans="46",
    )
    samples.append(s)

print(f"  Generated {len(samples)} total (added multi-hop)")

# ═══════════════════════════════════════════════════════════════════
# CATEGORY 5: HARD DISTINCTIONS (30 samples)
# ═══════════════════════════════════════════════════════════════════
hard_distinction_items = [
    ("What shade of red is this object?",
     "Identify the exact red tone of this item.",
     "Crimson", "Scarlet",
     "What is the hex code for this color?", "#FF2400",
     "What is the difference between crimson and scarlet?",
     "Deep blue-red shade", "Scarlet is more orange-red than crimson",
     "How does scarlet differ from crimson?"),
    ("What species of oak tree is this?",
     "Identify the specific oak species shown.",
     "White Oak", "English Oak",
     "What is this tree's scientific name?", "Quercus robur",
     "How do you tell white oak from English oak?",
     "European deciduous Quercus", "Leaf lobe depth and acorn stalk length",
     "What distinguishes white oak from English oak?"),
    ("What type of granite is this countertop?",
     "Identify the specific granite variety.",
     "Kashmir White", "Colonial White granite",
     "Where is this granite quarried?", "India",
     "How does Kashmir White differ from Colonial White?",
     "Light-colored Indian igneous stone", "Pattern density and background tone vary slightly",
     "What is the visual difference between these granites?"),
    ("Which subspecies of tiger is shown?",
     "Identify the specific tiger subspecies.",
     "Bengal Tiger", "Indochinese Tiger",
     "What is the population of this subspecies?", "About 250",
     "How does the Indochinese differ from Bengal tiger?",
     "Southeast Asian Panthera tigris", "Smaller body size and darker coloration",
     "What distinguishes Indochinese from Bengal tigers?"),
    ("What type of cumulus cloud is this?",
     "Identify the specific cumulus classification.",
     "Cumulus congestus", "Cumulus mediocris",
     "At what altitude does it form?", "2,000-6,000 meters",
     "How does cumulus mediocris differ from congestus?",
     "Mid-development fair weather cloud", "Less vertical extent and flatter tops",
     "What distinguishes cumulus mediocris from congestus?"),
    ("What specific alloy is this metal?",
     "Identify the exact metal alloy shown.",
     "316 Stainless Steel", "304 Stainless Steel",
     "What is the nickel content?", "8-10.5%",
     "How does 304 differ from 316 stainless?",
     "Austenitic chromium-nickel alloy", "316 has added molybdenum for corrosion resistance",
     "What is the key difference between 304 and 316 stainless steel?"),
    ("What wine grape variety is this?",
     "Identify the specific wine grape.",
     "Merlot", "Cabernet Franc",
     "What region is this grape from?", "Loire Valley",
     "How does Cabernet Franc differ from Merlot?",
     "French red wine variety", "More herbaceous and lighter body",
     "What distinguishes Cabernet Franc from Merlot?"),
    ("What specific breed of chicken is this?",
     "Identify the chicken breed shown.",
     "Rhode Island Red", "New Hampshire Red",
     "When was this breed developed?", "1915",
     "How do these two breeds differ?",
     "American red-feathered dual-purpose fowl", "New Hampshire is lighter and matures faster",
     "What distinguishes New Hampshire Red from Rhode Island Red chickens?"),
    ("What exact shade of blue is the sky in this image?",
     "Identify the precise blue tone of the sky.",
     "Cerulean", "Azure",
     "What is the wavelength of this blue?", "480-490 nm",
     "How does cerulean differ from azure?",
     "Upper atmosphere scattered light tone", "Cerulean has slight green tint, azure is deeper",
     "How does cerulean blue differ from azure blue?"),
    ("What type of basalt is this formation?",
     "Identify the specific basalt type shown.",
     "Flood basalt", "Columnar basalt",
     "How are these columns formed?", "Slow cooling and contraction",
     "How does flood basalt differ from columnar?",
     "Hexagonal prismatic volcanic rock", "Flood basalt covers vast areas, columnar is local fracturing",
     "What is the difference between flood basalt and columnar basalt?"),
    ("What specific type of marble is this?",
     "Identify the exact marble variety.",
     "Calacatta", "Carrara White",
     "Where is this marble quarried?", "Tuscany, Italy",
     "How does Calacatta differ from Carrara?",
     "Italian metamorphic decorative stone", "Calacatta has bolder, more dramatic veining",
     "What distinguishes Calacatta from Carrara marble?"),
    ("What exact rose variety is this?",
     "Identify the specific rose cultivar.",
     "Peace Rose", "Double Delight",
     "When was this variety introduced?", "1977",
     "How does Double Delight differ from Peace?",
     "Hybrid tea bicolor fragrant bloom", "Double Delight has red-edged cream petals with stronger scent",
     "What distinguishes Double Delight from Peace roses?"),
    ("What specific type of wool is this?",
     "Identify the exact wool variety.",
     "Merino", "Corriedale",
     "What is the fiber diameter?", "24-31 microns",
     "How does Corriedale differ from Merino?",
     "Fine-fiber sheep textile", "Corriedale is coarser with more crimp",
     "What distinguishes Corriedale wool from Merino?"),
    ("What subspecies of wolf is shown?",
     "Identify the specific wolf subspecies.",
     "Gray Wolf", "Timber Wolf",
     "What is the difference?", "Timber wolf is a common name for the gray wolf subspecies in eastern North America",
     "Are gray wolf and timber wolf the same?",
     "North American Canis lupus", "Largely interchangeable terms, timber wolf refers to C.l. lycaon",
     "Is the timber wolf the same as the gray wolf?"),
    ("What type of volcanic eruption produced this?",
     "Identify the eruption type that formed this.",
     "Strombolian", "Vulcanian",
     "What is the VEI rating?", "2-3",
     "How does Vulcanian differ from Strombolian?",
     "Explosive intermediate volcanic event", "Vulcanian is more explosive with denser ash columns",
     "What distinguishes Vulcanian from Strombolian eruptions?"),
    ("What specific species of salmon is this?",
     "Identify the salmon species shown.",
     "Sockeye salmon", "Coho salmon",
     "What is the average weight?", "3.5-5.5 kg",
     "How does Coho differ from Sockeye?",
     "Pacific anadromous salmonid", "Coho has silver sides, Sockeye turns red when spawning",
     "How do you distinguish Coho from Sockeye salmon?"),
    ("What variety of honey is this?",
     "Identify the specific honey type.",
     "Acacia honey", "Clover honey",
     "What is the glycemic index?", "32",
     "How does clover honey differ from acacia?",
     "Light amber floral nectar product", "Clover is milder and lighter than acacia",
     "What distinguishes clover from acacia honey?"),
    ("What exact type of quartz is this?",
     "Identify the specific quartz variety.",
     "Rose Quartz", "Milky Quartz",
     "What causes the color?", "Microscopic titanium or iron inclusions",
     "How does milky quartz differ from rose quartz?",
     "Translucent silicon dioxide crystal", "Milky quartz is white due to fluid inclusions",
     "What makes milky quartz different from rose quartz?"),
    ("What specific sub-breed of German Shepherd is this?",
     "Identify the exact German Shepherd line.",
     "Working Line", "Show Line",
     "What is the key trait difference?", "Show lines have more angulated hindquarters",
     "How do working and show lines differ?",
     "Deutsche Schäferhund variant", "Working lines have straighter backs and more drive",
     "What distinguishes working line from show line German Shepherds?"),
    ("What type of tea is this precisely?",
     "Identify the exact tea variety.",
     "Sencha", "Gyokuro",
     "What makes this tea special?", "Shade-grown for 20 days before harvest",
     "How does Gyokuro differ from Sencha?",
     "Japanese green tea steamed variety", "Gyokuro is shade-grown giving sweeter, more umami flavor",
     "What distinguishes Gyokuro from Sencha green tea?"),
    ("What specific mortar joint style is used?",
     "Identify the exact mortar joint type.",
     "Concave joint", "V-joint",
     "What tool is used for this joint?", "V-shaped jointing tool",
     "How does a V-joint differ from concave?",
     "Masonry pointing technique", "V-joint has a sharper center ridge",
     "What distinguishes a V-joint from a concave mortar joint?"),
    ("What specific type of volcanic glass is this?",
     "Identify the exact volcanic glass type.",
     "Obsidian", "Pitchstone",
     "What is the silica content?", "65-70%",
     "How does pitchstone differ from obsidian?",
     "Dark glassy volcanic extrusive rock", "Pitchstone has higher water content and resinous luster",
     "What distinguishes pitchstone from obsidian?"),
    ("What exact subspecies of brown bear is this?",
     "Identify the specific brown bear subspecies.",
     "Kodiak Bear", "Grizzly Bear",
     "What is the key size difference?", "Kodiak can reach 680 kg, grizzly typically 270 kg",
     "How does a grizzly compare to a Kodiak?",
     "North American Ursus arctos subspecies", "Kodiak is larger due to island gigantism and salmon diet",
     "What makes Kodiak bears different from grizzly bears?"),
    ("What specific type of jazz is being played?",
     "Identify the exact jazz sub-genre.",
     "Bebop", "Hard bop",
     "When did this style emerge?", "Mid-1950s",
     "How does hard bop differ from bebop?",
     "Post-war improvisational American music", "Hard bop incorporates more blues and gospel influences",
     "What distinguishes hard bop from bebop?"),
    ("What specific cement type is used here?",
     "Identify the exact cement type.",
     "Type I Portland", "Type II Portland",
     "What is the key property difference?", "Type II has moderate sulfate resistance",
     "How does Type II Portland differ from Type I?",
     "Hydraulic calcium silicate binder", "Type II has lower C3A content for sulfate environments",
     "What distinguishes Type II from Type I Portland cement?"),
    ("What variety of lettuce is this?",
     "Identify the specific lettuce type.",
     "Romaine", "Butterhead",
     "What is the texture difference?", "Butterhead has softer, more tender leaves",
     "How does butterhead differ from romaine?",
     "Crisp salad green Lactuca sativa", "Butterhead forms loose heads with silky leaves",
     "What distinguishes butterhead from romaine lettuce?"),
    ("What type of leather is this?",
     "Identify the exact leather type.",
     "Full-grain", "Top-grain",
     "How do they differ?", "Top-grain is sanded to remove imperfections",
     "What distinguishes full-grain from top-grain leather?",
     "Processed animal hide", "Full-grain retains the entire grain surface including imperfections",
     "How does full-grain leather differ from top-grain?"),
    ("What specific type of cast iron is this?",
     "Identify the exact cast iron type.",
     "Gray cast iron", "Ductile cast iron",
     "What is the key molecular difference?", "Ductile has spheroidal graphite vs flake graphite",
     "How does ductile differ from gray cast iron?",
     "Iron-carbon alloy casting", "Ductile iron has nodular graphite making it stronger and less brittle",
     "What distinguishes ductile from gray cast iron?"),
    ("What specific species of trout is this?",
     "Identify the exact trout species.",
     "Rainbow Trout", "Brown Trout",
     "What is the distinguishing mark?", "Brown trout has red-orange spots with pale halos",
     "How does brown trout differ from rainbow trout?",
     "Freshwater salmonid game fish", "Brown trout has darker coloration with distinct red spots",
     "What distinguishes brown trout from rainbow trout?"),
    ("What precise shade of white is this paint?",
     "Identify the exact white paint shade.",
     "Swiss Coffee", "Navajo White",
     "What is the LRV of this color?", "65",
     "How does Navajo White differ from Swiss Coffee?",
     "Off-white warm-toned paint shade", "Navajo White is warmer with more yellow-peach undertone",
     "What distinguishes Navajo White from Swiss Coffee paint colors?"),
]

for item in hard_distinction_items:
    imgs = pick(3)
    s = make_sample(
        src=item[0], rephrase=item[1], pred=item[2], alt=item[3],
        image=imgs[0], image_reph=imgs[1],
        loc="What planet do we live on?",
        loc_ans="Earth",
        m_loc_q="Is the image taken indoors or outdoors?",
        m_loc_a="Outdoors", m_loc_img=imgs[2],
        port_q=item[4], port_a=item[5],
        te_src=item[6], te_pred=item[7], te_alt=item[8],
        te_reph=item[9],
        te_loc="What is the smallest prime number?",
        te_loc_ans="2",
    )
    samples.append(s)

print(f"  Generated {len(samples)} total (added hard distinctions)")

# ═══════════════════════════════════════════════════════════════════
# SAVE
# ═══════════════════════════════════════════════════════════════════
assert len(samples) == 200, f"Expected 200 samples, got {len(samples)}"

random.shuffle(samples)

with open("datasets/adversarial_v2_hard.json", "w", encoding="utf-8") as f:
    json.dump(samples, f, indent=2, ensure_ascii=False)

print(f"\n✓ Saved datasets/adversarial_v2_hard.json ({len(samples)} samples)")
print(f"  Category breakdown: 50 ambiguity, 40 conflicting, 40 retrieval traps, 40 multi-hop, 30 hard distinctions")
